title: >
 <div align="center">
    <p><strong>Amit Thakuri</strong></p>
  </div>
logo: /assets/dp.jpeg
description: >
  <div align="center">
    <p><strong>IT and Cyber Enthusiast</strong></p>
  </div>
show_downloads: false
google_analytics: G-9R8QKEJXE9
theme: jekyll-theme-cayman
sass:
  style: compressed

